---
kind: pipeline
name: default

steps:
  - name: publish
    image: python:3.7
    commands:
      - pip install -U pip pip-tools
      - pip-compile --generate-hashes requirements.in > requirements.txt
      - pip install --require-hashes -r requirements.txt
      - pytest ./tests
      - black ./src
      - mypy ./src
      - pyre --source-directory ./src check
