version: "3"

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./src:/src
      - ./tests:/tests
    command: flask run --host=0.0.0.0 --reload
  # elasticsearch:
  #   image: "elasticsearch:6.8.3"
  #   ports:
  #     - "9200:9200"
  #     - "9300:9300"
  #   environment:
  #     - bootstrap.memory_lock=true
  #     - discovery.type=single-node
  #     - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
  #     - cluster.routing.allocation.disk.threshold_enabled=false
  #   ulimits:
  #     memlock:
  #       soft: -1
  #       hard: -1
  #   user: "elasticsearch"
